### ISSUE TITLE
Merging history 2

### ISSUE THREAD

**Issue by tomwright01** [tomwright01/swc-modular-sql#3]
Got myself completely twisted up with the previous attempt so started again. Going much better this time (I understand the process a little better).

```
git checkout -b novice-sql swc/master
git filter-branch -f --subdirectory-filter novice/sql --prune-empty
```

> commit f16f7b8671bd9a4eb629a8e04b8954487d198a34
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Sun Feb 16 08:17:08 2014 -0500>
> 
>    Reorganizing material to put novice + intermediate at top level

```
git show --stat 'swc/master^{/Reorganizing material to put novice}'
```
# same commit on bc

> commit b8c7dc3b75002b898f26df551a2c646d78e3aaca
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Sun Feb 16 08:17:08 2014 -0500

```
git checkout -b sql-novice b8c7dc^
# new branch anchored at commit before last one in novice-sql
git filter-branch -f --subdirectory-filter sql/novice --prune-empty
# filter changes affection sql/novice
```

```
git checkout novice-sql
#back to working branch
ORPHAN_COPY_COMMIT=$(git rev-parse 'HEAD^{/Reorganizing material to put novice}')
#find hash for last commit
git rebase -p --onto sql-novice "${ORPHAN_COPY_COMMIT}"
#copy commit log from sql-novice
```
# Earliest commit is now

> commit 5d8d8bec5a15f619937ceb4e723f1ac14f06c706
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Sat Nov 2 07:42:09 2013 -0400
> 
>    Laying out new material
# Looks pretty original
# However compare with bc

```
diff -u <(git ls-tree -r swc/master -- novice/sql | sed 's|novice/sql/||') <(git ls-tree -r HEAD^)
```
# looks like 08-create.md is not the same version

```
git log --oneline --stat --follow swc/master -- novice/sql/08-create.md
```

> 5d29354 Modified build to generate Markdown files for IPython 
> Notebooks in the source directories so that the Jekyll build will > put all the files in the right places.  (Having a separate CACHED > directory is cleaner, but then we have to move or patch files 
> after the fact to make links resolve.)
> {cached/novice => novice}/sql/08-create.md | 0
> 1 file changed, 0 insertions(+), 0 deletions(-)
# looks like a file was moved from cached/novice

```
git show --stat 'swc/master^{/Modified build to generate Markdown}'
```
# create a new branch

```
git checkout bc
git checkout -b cached-novice 5d29354^
git filter-branch -f --subdirectory-filter cached/novice/sql --prune-empty
```

```
git checkout novice-sql
ORPHAN_COPY_COMMIT=$(git rev-parse 'HEAD^{/Modified build to generate Markdown}')

git rebase -p --onto cached-novice "${ORPHAN_COPY_COMMIT}"
```

> error: could not apply 4d5da0a... Adding links to reference material on appropriate pages
> 
> When you have resolved this problem, run "git rebase --continue".
> If you prefer to skip this patch, run "git rebase --skip" instead.
> To check out the original branch and stop rebasing, run "git rebase --abort".
> Could not pick 4d5da0acbffd551d8f7eedd7d7ffd9764ddac0f4

**Comment by tomwright01** [comment]
@wking suggested I need to follow these http://git.tremily.us/?p=swc-testing-nose.git;a=commit;h=dd8cf3059215fba494cacfb089ee519c2cfffd46 instructions to resolve this error. However while I sort of understand what they do I'm not sure which branch to run them against, or when.

Should this be run against the 'novice-sql' branch (the one where I'm collecting all this history) or against the cached-novice branch (the one with old history I need to merge).

If it's in the cached-novice branch should it be run before I start the final git rebase?
If in the novice-sql branch should I run the fix, then git rebase --continue, or should I abort, fix then rebase?

**Comment by wking** [comment]
On Mon, Nov 10, 2014 at 01:35:51PM -0800, Tom Wright wrote:

> @wking suggested I need to follow these
> http://git.tremily.us/?p=swc-testing-nose.git;a=commit;h=dd8cf3059215fba494cacfb089ee519c2cfffd46
> instructions to resolve this error. However while I sort of
> understand what they do I'm not sure which branch to run them
> against, or when.

So you want to abort the rebase that gave you:

  error: could not apply 4d5da0a

Then you have two histories:

  o---o---a---b---o---o  (novice-sql)

  o---o---c              (cached-novice)

Where (b) is your version of “Modified build to generate Markdown
files for IPython”.  You want to change that history to:

  o---o---a---b'---o'---o'  (novice-sql)
                   /
  o---o---c--

where (b') is now a merge commit with parents (a) and (c).  The
dd8cf305 commit message explains how to build that:
1. Find the hashes for a, b, and c.
2. Make an entry in .git/info/grafts:
   
   $HASH_FOR_B $HASH_FOR_A $HASH_FOR_C
3. With novice-sql checked out, run ‘git filter-branch’ to bake in the
   graft.
4. Remove the now-unnecessary .git/info/grafts.

**Comment by tomwright01** [comment]
Ok, lets start by finding b

```
git checkout novice-sql
git log --oneline |grep "Modified build to generate Markdown files"
```

> 23b7789 Modified build to generate Markdown files

'git show 23b7789'

> commit 23b778910337720eba4e20fba4827bb13bca8cc0
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Mon Mar 3 10:54:21 2014 -0500

a is the parent commit

`git show 23b7789^`

> commit 32d0cc550d3191f7bc79fdcc606bd015ddc859e6
> Merge: fc88267 ac44393
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Fri Feb 28 07:51:05 2014 -0500
> 
>    Merge branch 'sticking-with-jekyll' of github.com:gvwilson/bc into sticking-with-jekyll

c is the last commit in cached-novice

```
git checkout cahced-novice
git log |head -n6
```

> commit 928b30c3f1b7f8b2bfb1cc07a92fd9555d9c82de
> Merge: 367eff4 09a7de0
> Author: Greg Wilson gvwilson@third-bit.com
> Date:   Fri Feb 28 07:51:05 2014 -0500
> 
>    Merge branch 'sticking-with-jekyll' of github.com:gvwilson/bc into sticking-with-jekyll

Lets make the entry in .git/info/grafts

```
git checkout novice-sql
echo 23b778910337720eba4e20fba4827bb13bca8cc0 \
32d0cc550d3191f7bc79fdcc606bd015ddc859e6 \
928b30c3f1b7f8b2bfb1cc07a92fd9555d9c82de \
> .git/info/grafts
```

```
git filter-branch -f
```

> Rewrite 5632afa5fae294f6b6ecb098561e135e4ec7dd4d (45/45)
> Ref 'refs/heads/novice-sql' was rewritten

`rm .git/info/grafts`

<s>
OK, now I should be able to get the history from cached-novice

```
<s>
ORPHAN_COPY_COMMIT=$(git rev-parse 'HEAD^{/Modified build to generate Markdown}')
echo ORPHAN_COPY_COMMIT
</s>
```

> <s>b53c4bed086a7e301dcf91d9c6f2cc7e6c576a99</s>
> 
> ```
> <s>
> git rebase -p --onto cached-novice "${ORPHAN_COPY_COMMIT}"
> </s>
> ```
> 
> <s>error: could not apply 6414be3... Adding links to reference material on appropriate pages</s>
> <s>
> Damn, looks like I didn't find the correct split
> </s>
> `<s>git rebase --abort</s>`

**Comment by wking** [comment]
On Tue, Nov 11, 2014 at 07:19:13AM -0800, Tom Wright wrote:

> git checkout novice-sql
> …
> git checkout cahced-novice
> git log |head -n6
> …
> git filter-branch -f

You should be filter-branching the novice-sql branch.  Did you get
back onto that branch before running your filter-branch?  Other than
that, this graft looked good to me.

> OK, now I should be able to get the history from cached-novice

After the grafting filter-branch, you should already have the
cached-novice history integrated (with the b' merge).  No need for a
further rebase onto cached-novice.

**Comment by tomwright01** [comment]
Alright...
Sounds like I'm good to proceed.
Doing another diff with the swc/bc repo looks like there are still differences between my copy and hte original. I think commit 

> 47de286 1. Storing the generated files so that people who don't use those tools won't have to regenerate them. 2. Modifying .gitignore to reflect this. 3. Updating the Makefile to run Jekyll exactly once.
>  translated/novice/sql/08-create.md | 102 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> 1 file changed, 102 insertions(+)

Probably has something to do with this, big changes to the file 08-create.md occured in the translated/novice/sql file structure, guess I should go collect them.

**Comment by wking** [comment]
On Tue, Nov 11, 2014 at 09:31:11AM -0800, Tom Wright wrote:

> > 47de286 1. Storing the generated files…
> >  translated/novice/sql/08-create.md | 102 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> > 1 file changed, 102 insertions(+)

I'm not sure what translated/novice/sql was all about.  Maybe you
don't need these changes at all?

**Comment by tomwright01** [comment]
> I'm not sure what translated/novice/sql was all about.  Maybe you
> don't need these changes at all?

I just checked out and filtered on that structure, seems there is nothing there. I guess this was just a temp directory that got renamed to cached, I already have history from cached so looks like I'm done with this bit?

Unless anyone thinks there is more history I have missed I'll move on to putting this new repo into the new lesson structure.

Thanks @wking for your patience.

**Comment by wking** [comment]
On Tue, Nov 11, 2014 at 09:56:05AM -0800, Tom Wright wrote:

> Unless anyone thinks there is more history I have missed I'll move
> on to putting this new repo into the new lesson structure.

Does a tree diff between your current branch and bc/gh-pages'
novice/sql match?  See, for example, the ‘ls-tree’ calls in
wking/swc-modular-shell#4.

**Comment by tomwright01** [comment]
bc/gh-pages or bc/master?
`diff -u <(git ls-tree -r swc/master -- novice/sql | sed 's|novice/sql/||') <(git ls-tree -r HEAD^)`

> --- /dev/fd/63    2014-11-11 13:39:33.199822985 -0500
> +++ /dev/fd/62    2014-11-11 13:39:33.203822985 -0500
> @@ -14,8 +14,8 @@
>  100644 blob 1ca16522abd5b57eab83cc241e7b5938262866aa 06-agg.md
>  100644 blob 93761c51a1821a27219ee179f622e1642408ff25 07-join.ipynb
>  100644 blob 6fbf75c0549c79c4e7678008675fcaf502aa7947 07-join.md
> -100644 blob bb5693b057bd8b8ee3012b40de59cebf257683db 08-create.ipynb
> -100644 blob f8e6c7249c90b7639dbbb829651fb01447813f68 08-create.md
> +100644 blob e6e044c41d3e30b3660e684963f8e81b86f53887 08-create.ipynb
> +100644 blob a32ef850c4430f40a6278952bc9d92a202c9c490 08-create.md
>  100644 blob 63461bae5271a9292a030ba84c68049a309a9ecc 09-prog.ipynb
>  100644 blob 3c87f69cc467e66c82ee49b1e5ddbb3f0c932c6c 09-prog.md
>  100644 blob 58dd4fb88a4edf1b584403d4b54a740844be3f99 README.txt

There still seems to be a difference in the 08-create.\* lesson, however my current version is the same as the one in bc/master

`git diff swc/gh-pages novice-sql -- 08-create.md`

> diff --git a/08-create.md b/08-create.md
> new file mode 100644
> index 0000000..f8e6c72
> --- /dev/null
> +++ b/08-create.md
> @@ -0,0 +1,216 @@
> ...

**Comment by wking** [comment]
On Tue, Nov 11, 2014 at 10:50:12AM -0800, Tom Wright wrote:

> `diff -u <(git ls-tree -r swc/master -- novice/sql | sed 's|novice/sql/||') <(git ls-tree -r HEAD^)`

You probably want HEAD instead of HEAD^.

**Comment by tomwright01** [comment]
Thanks. That gets rid of the differences for create.md

**Comment by tomwright01** [comment]
It does seem there are still some differences in gh-pages 

```
 diff -u <(git ls-tree -r swc/gh-pages -- novice/sql | sed 's|novice/sql/||') <(git ls-tree -r HEAD)
```

> --- /dev/fd/63    2014-11-11 16:03:30.928111783 -0500
> +++ /dev/fd/62    2014-11-11 16:03:30.928111783 -0500
> @@ -18,7 +18,7 @@
>  100644 blob f8e6c7249c90b7639dbbb829651fb01447813f68 08-create.md
>  100644 blob 63461bae5271a9292a030ba84c68049a309a9ecc 09-prog.ipynb
>  100644 blob 3c87f69cc467e66c82ee49b1e5ddbb3f0c932c6c 09-prog.md
> -100644 blob 31ccb7e4298edb58a50beb4fbfd2df00e57eb4db README.txt
> +100644 blob 58dd4fb88a4edf1b584403d4b54a740844be3f99 README.txt
>  100644 blob bfba7fbc70f1612042ac5d13dad7a6f9bb2969da gen-survey-database.sql
>  100644 blob ed2b9a03fca14e168999d1f5c6925d0ad491e0fa img/sql-aggregation.odg
>  100644 blob 89cef2bf7625e99ab3b03938a9efa19fed140136 img/sql-aggregation.png

I'll see if I can merge them.

**Comment by tomwright01** [comment]
```
git checkout -b ghpages swc/gh-pages
git filter-branch -f --subdirectory-filter novice/sql --prune-empty
git log -- README.txt
```

> commit 60339671c3636bc0eed4cb767ff7ced47a5760e0
> Author: Daniel Chen Maveri2k@yahoo.com
> Date:   Wed Oct 8 18:35:02 2014 -0400
> 
>    only keep n,median; remove mean,min,max
> 
> commit fba466b6c4ddc501dacf837a082d404992a60724
> Author: Daniel Chen Maveri2k@yahoo.com
> Date:   Tue Oct 7 18:04:09 2014 -0400
>     times for shell, python, git, sql

`git show 'swc/gh-pages^{/times for shell}'`

> commit 81b77c3456f2e5a71ec80e8f879ee969dbf3d17b

`git show 'swc/gh-pages^{/only keep n,median}'`

> commit e28d1084b47fd3353053dc8141c08f398c376ba1

These seem to be the two commits I'm missing

Going to create a test branch

```
git checkout novice-sql
git branch -b novice-sql-test
```

`git show fba466b6c4ddc501dacf837a082d404992a60724 -- README.txt`
This command creates a patch from the SHA and applies it to the tree, but doesn't keep the original information about the commit which is the point of this. I could just add the relevant info to the commit message but that seems like cheating

**Comment by tomwright01** [comment]
```
git cherry-pick fba466b6c4dd
git cherry-pick 60339671c3
```

I think the order was important

**Comment by tomwright01** [comment]
Ok, again from @wking, who has held my hand through this process like a hero (compliments to him, blame is all mine).
just cherry picking the commits was ok, but missed the merge by @gvwilson.

Undo the last two commits
`git reset --hard HEAD~2`

Going to create a new branch, apply the commits and 'fake' the merge message

```
git checkout -b wip
git cherry-pick fba466b6c4dd
git cherry-pick 60339671c3
git checkout novice-sql
GIT_AUTHOR_NAME='Greg Wilson' GIT_AUTHOR_EMAIL='gvwilson@software-carpentry.org' GIT_AUTHOR_DATE='Sun Nov 2 16:46:38 2014 -0500' git merge --no-ff wip
```

Fill in the same merge commit message from:
`git show 'swc/gh-pages^{/Merge pull request #789}'`

**Comment by tomwright01** [comment]
Closing this issue since merge is complete.
